-- Capacitación 1 con 8 empleados
INSERT INTO `bd_semana05`.`tb_emp_capa` VALUES (1, 1);
INSERT INTO `bd_semana05`.`tb_emp_capa` VALUES (2, 1);
INSERT INTO `bd_semana05`.`tb_emp_capa` VALUES (3, 1);
INSERT INTO `bd_semana05`.`tb_emp_capa` VALUES (4, 1);
INSERT INTO `bd_semana05`.`tb_emp_capa` VALUES (5, 1);
INSERT INTO `bd_semana05`.`tb_emp_capa` VALUES (6, 1);
INSERT INTO `bd_semana05`.`tb_emp_capa` VALUES (7, 1);
INSERT INTO `bd_semana05`.`tb_emp_capa` VALUES (8, 1);

-- Capacitación 2 con 20 empleados
INSERT INTO `bd_semana05`.`tb_emp_capa` VALUES (1, 2);
INSERT INTO `bd_semana05`.`tb_emp_capa` VALUES (2, 2);
INSERT INTO `bd_semana05`.`tb_emp_capa` VALUES (3, 2);
INSERT INTO `bd_semana05`.`tb_emp_capa` VALUES (4, 2);
INSERT INTO `bd_semana05`.`tb_emp_capa` VALUES (5, 2);
INSERT INTO `bd_semana05`.`tb_emp_capa` VALUES (6, 2);
INSERT INTO `bd_semana05`.`tb_emp_capa` VALUES (7, 2);
INSERT INTO `bd_semana05`.`tb_emp_capa` VALUES (8, 2);
INSERT INTO `bd_semana05`.`tb_emp_capa` VALUES (9, 2);
INSERT INTO `bd_semana05`.`tb_emp_capa` VALUES (10, 2);
INSERT INTO `bd_semana05`.`tb_emp_capa` VALUES (11, 2);
INSERT INTO `bd_semana05`.`tb_emp_capa` VALUES (12, 2);
INSERT INTO `bd_semana05`.`tb_emp_capa` VALUES (13, 2);
INSERT INTO `bd_semana05`.`tb_emp_capa` VALUES (14, 2);
INSERT INTO `bd_semana05`.`tb_emp_capa` VALUES (15, 2);
INSERT INTO `bd_semana05`.`tb_emp_capa` VALUES (16, 2);
INSERT INTO `bd_semana05`.`tb_emp_capa` VALUES (17, 2);
INSERT INTO `bd_semana05`.`tb_emp_capa` VALUES (18, 2);
INSERT INTO `bd_semana05`.`tb_emp_capa` VALUES (19, 2);
INSERT INTO `bd_semana05`.`tb_emp_capa` VALUES (20, 2);